name: Geek's Attitute
description: Ever tried.Ever failed.No matter.Try again.Fail again.
meta_description: "Geek's Attitute"

markdown: redcarpet
pygments: true
logo: false
paginate: 5
permalink: /:title

# Details for the RSS feed generator
url:            'www.wangwenxin.com'
author:         'Wesley Wang'


